# Generated by Django 5.2.7 on 2026-06-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_alter_appointment_created_at_alter_appointment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('appointment_created', 'Cita creada')], max_length=50, verbose_name='tipo de evento')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment', verbose_name='cita')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='canal')),
                ('destination', models.CharField(max_length=254, verbose_name='destino')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('error_message', models.TextField(blank=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notificaciones.notification', verbose_name='notificación')),
            ],
            options={
                'verbose_name': 'envío de notificación',
                'verbose_name_plural': 'envíos de notificación',
                'ordering': ['channel'],
                'constraints': [models.UniqueConstraint(fields=('notification', 'channel'), name='unique_notification_channel')],
            },
        ),
    ]
