# Generated by Django 5.2.7 on 2026-06-13 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificios', '0003_alter_building_address_alter_building_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='fecha')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'día festivo',
                'verbose_name_plural': 'días festivos',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_appointments', models.PositiveIntegerField(default=1, help_text='Número máximo de citas que se pueden atender a la misma hora.', verbose_name='citas simultáneas máximas')),
            ],
            options={
                'verbose_name': 'configuración del sistema',
                'verbose_name_plural': 'configuración del sistema',
            },
        ),
        migrations.CreateModel(
            name='BuildingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día de la semana')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('end_time', models.TimeField(verbose_name='hora de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='edificios.building', verbose_name='edificio')),
            ],
            options={
                'verbose_name': 'horario de edificio',
                'verbose_name_plural': 'horarios de edificios',
                'ordering': ['day_of_week'],
                'unique_together': {('building', 'day_of_week')},
            },
        ),
    ]
