# Generated by Django 5.2.7 on 2026-06-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_seed_default_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='max_advance_booking_days',
            field=models.PositiveIntegerField(default=30, help_text='Cantidad máxima de días hacia adelante en los que se pueden agendar citas.', verbose_name='anticipación máxima en días'),
        ),
    ]
