# Generated by Django 5.2.7 on 2026-08-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_systemsettings_max_advance_booking_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='slot_interval_minutes',
            field=models.PositiveSmallIntegerField(choices=[(15, 'Cada 15 minutos'), (30, 'Cada 30 minutos'), (60, 'Cada 60 minutos')], default=30, help_text='Define cada cuántos minutos se muestran horarios disponibles para agendar.', verbose_name='intervalo de horarios'),
        ),
    ]
