# Generated by Django 5.2.7 on 2026-06-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AddField(
            model_name='service',
            name='accent',
            field=models.CharField(choices=[('blue', 'Azul'), ('red', 'Rojo'), ('dark', 'Azul oscuro')], default='blue', max_length=10, verbose_name='color de la tarjeta'),
        ),
        migrations.AddField(
            model_name='service',
            name='badge',
            field=models.CharField(blank=True, help_text='Texto corto que se muestra en la tarjeta, por ejemplo "MÁS VENDIDO".', max_length=40, verbose_name='etiqueta'),
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='orden'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='duración (minutos)'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, help_text='Una característica por línea. Antepón "!" a una línea para mostrarla como no incluida (tachada).', verbose_name='características'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='destacado'),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
    ]
