# Generated by Django 5.2.7 on 2026-08-25 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_vehicles_from_profiles(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    Vehicle = apps.get_model('accounts', 'Vehicle')

    for profile in UserProfile.objects.exclude(car_plate=''):
        Vehicle.objects.get_or_create(
            user_id=profile.user_id,
            plate=profile.car_plate,
            defaults={
                'brand': profile.car_brand or 'Sin marca',
                'model': profile.car_model or 'Sin modelo',
                'color': profile.car_color or 'Sin color',
                'parking_level': profile.parking_level or 'Sin sótano',
                'parking_number': profile.parking_number or 'Sin parqueo',
                'is_default': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_vehicle_parking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80, verbose_name='marca del auto')),
                ('model', models.CharField(max_length=80, verbose_name='modelo')),
                ('color', models.CharField(max_length=40, verbose_name='color')),
                ('plate', models.CharField(max_length=20, verbose_name='placa')),
                ('parking_level', models.CharField(max_length=40, verbose_name='sótano')),
                ('parking_number', models.CharField(max_length=40, verbose_name='número de parqueo')),
                ('is_default', models.BooleanField(default=False, verbose_name='predeterminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['-is_default', 'brand', 'model', 'plate'],
                'constraints': [models.UniqueConstraint(fields=('user', 'plate'), name='unique_vehicle_plate_per_user')],
            },
        ),
        migrations.RunPython(create_vehicles_from_profiles, migrations.RunPython.noop),
    ]
