# Generated by Django 5.2.7 on 2026-06-12 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellido')),
                ('phone_number', models.CharField(max_length=20, verbose_name='numero de telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('date', models.DateField(verbose_name='fecha')),
                ('time', models.TimeField(verbose_name='hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['date', 'time'],
            },
        ),
    ]
