# Generated by Django 5.2.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_status'),
        ('membresia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='membership_subscription',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='appointments',
                to='membresia.membershipsubscription',
                verbose_name='membresía aplicada',
            ),
        ),
        migrations.AddField(
            model_name='appointment',
            name='uses_membership',
            field=models.BooleanField(
                default=False,
                help_text='Indica que esta cita no requiere pago individual porque usa la suscripción.',
                verbose_name='cubierta por membresía',
            ),
        ),
    ]
