# Generated by Django 5.2.7

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0004_update_basico_badge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('tier_label', models.CharField(max_length=40, verbose_name='etiqueta del plan')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='ícono')),
                ('accent', models.CharField(choices=[('blue', 'Azul'), ('red', 'Rojo'), ('midnight', 'Medianoche')], default='blue', max_length=12, verbose_name='color de la tarjeta')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio mensual')),
                ('savings_label', models.CharField(blank=True, max_length=120, verbose_name='mensaje de ahorro')),
                ('features', models.TextField(blank=True, help_text='Un beneficio por línea.', verbose_name='beneficios')),
                ('monthly_wash_limit', models.PositiveIntegerField(blank=True, help_text='Déjalo vacío para lavados ilimitados dentro de los servicios incluidos.', null=True, verbose_name='lavados incluidos por mes')),
                ('covers_all_services', models.BooleanField(default=False, verbose_name='incluye todos los servicios')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('featured_banner', models.CharField(blank=True, max_length=80, verbose_name='banda destacada')),
                ('is_available_for_purchase', models.BooleanField(default=False, help_text='Si está desactivado, se muestra como "Próximamente".', verbose_name='disponible para compra')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(blank=True, related_name='membership_plans', to='servicios.service', verbose_name='servicios incluidos')),
            ],
            options={
                'verbose_name': 'plan de membresía',
                'verbose_name_plural': 'planes de membresía',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='active', max_length=20, verbose_name='estado')),
                ('current_period_start', models.DateField(verbose_name='inicio del periodo')),
                ('current_period_end', models.DateField(verbose_name='fin del periodo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='membresia.membershipplan', verbose_name='plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'suscripción de membresía',
                'verbose_name_plural': 'suscripciones de membresía',
                'ordering': ['-current_period_end', '-created_at'],
            },
        ),
    ]
