# Generated by Django 5.2.7 on 2026-06-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0002_building_admins_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='building',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='building',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='número de teléfono'),
        ),
        migrations.AlterField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
    ]
