# Generated by Django 5.2.7 on 2026-06-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0003_alter_building_address_alter_building_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='accepts_appointments',
            field=models.BooleanField(default=True, help_text='Si está desactivado, no se podrán agendar nuevas citas en este edificio.', verbose_name='acepta citas'),
        ),
    ]
